remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
show_downloads: false
minimal_mistakes_skin: "dark"
timezone: UTC+1
locale: en-US
enable_copy_code_button: true
masthead_title: "Vicente García Andrade"

#SEARCH ENGINE
search: true
lunr:
  search_within_pages: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

author:
  home: "/"
  name: "Vicente García Andrade"
  avatar: "/assets/images/avatar.png"  #TODO: take a good photo
  bio: "Fractional CTO & Tech Strategist specializing in backend systems and technical leadership."
  location: "Madrid, Spain"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vicente-garcia-andrade/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Quierounnombre"

social:
  links:
    - "https://www.linkedin.com/in/vicente-garcia-andrade/"
    - "https://github.com/Quierounnombre"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
