openapi: 3.0.3
info:
  title: backend-template
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT



paths:
  /OAuthLogin:
    get:
      summary: OAuthLogin
      description: Send the user to the OAuth server, setting a "state" cookie, after that is redirected to the OAuthCallback, if the user is not sign up, it creates and adhoc user if the email is not used.
      responses:
        '301':
          description: Redirect to the OAuth provider.
        '500':
          description: Session didn't save, or auth URL generation failed.

  /OAuthCallback:
    get:
      summary: OAuthCallback
      description: Validates state token, exchanges auth code for tokens, verifies id_token, creates or logs in user, issues session JWT. The required fields are setted by OAuthLogin.
      parameters:
        - name: state
          in: cookie
          required: true
          schema: {type: string}
        - name: code
          in: query
          required: true
          schema: {type: string}
        - name: state
          in: query
          required: true
          schema: {type: string}
      responses:
        '200':
          description: User authenticated, session issued.
        '400':
          description: Missing/mismatched state, missing code, missing claims, user creation failed.
        '401':
          description: Missing state cookie, invalid id_token.
        '500':
          description: Session save failed.
        '502':
          description: Bad provider response, suspicious JWT by provider.

  /PassLogin:
    post:
      summary: PassLogin
      description: Logs the user when checking the password hash against the stored hash, issues a session JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: {type: string, format: email}
                password: {type: string, format: password}
      responses:
        '200':
          description: Login successful, JWT issued.
        '400':
          description: Bad format in the request/missing fields.
        '401':
          description: Invalid credentials.
        '500':
          description: Couldn't retrieve user from DB, Couldn't generate a JWT.

  /PassSignup:
    post:
      summary: PassSignup
      description: Creates a tmp user in the 2FA table, sending a 2FA code to the provided email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name]
              properties:
                email: {type: string, format: email}
                password: {type: string, format: password}
                name: {type: string, format: name}
      responses:
        '200':
          description: Sended a 2FA request to the user email.
        '400':
          description: Bad format in the request/missing fields.
        '500':
          description: Couldn't store a temp user in the 2FA table, couldn't send an email, weak password.

  /Validate_2FA/{id}:
    post:
      summary: Validate_2FA/{id}
      description: Validate the 2FA tmp user and move the user to Users table. The ID is setted when launching the email, and embeded in the link.
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string}
      responses:
        '200':
          description: Issue a JWT and move the user from the temp 2FA table, to the users table.
        '500':
          description: Couldn't retrieve user at the DB, user already exist, issue moving the user, Couldn't generate a JWT

  /PassReset:
    post:
      summary: PassReset
      description: Send a reset password to the email in the request, in the case the user dosen't exist it return still 200 but no email is sent.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email: {type: string, format: email}
      responses:
        '200':
          description: Send a email for continuing the pass reset process, or fake sending a email.
        '400':
          description: Missing key data in the request as the email
        '500':
          description: Couln't retrieve data from the DB, couldn't send an email.

  /Reset_pass_new/{id}:
    post:
      summary: Reset_pass_new/{id}
      description: Check the id and email, and if they are correct sets the user password to newpass, if newpass is as strong as policy dictate. Id is injected into the reset_pass request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, newpass]
              properties:
                email: {type: string, format: email}
                newpass: {type: string, format: password}
      responses:
        '200':
          description: Password has been succesfully reseted.
        '400':
          description: Missing email, newpass, or the whole body. Mismatch between request email and id email.
        '500':
          description: Missing id token in the DB, Couldn't erase the id token from the DB, Weak password.

  /Refresh:
    post:
      summary: Refresh
      description: Refresh the JWT token.
      responses:
        '200':
          description: Issues a new JWT.
        '500':
          description: JWT has expired.

  /Public-key:
    get:
      summary: Public-key
      description: Provide the public key, to ensure that the JWT is authentic by your services.
      responses:
        '200':
          description: Provided the RS256 current public key.
        '500':
          description: Error retrieving the current public key.

  /User/Profile:
    get:
      summary: User/Profile
      description: Return a profile data, it need to be autorize by the JWT.
      responses:
        '200':
          description: Send a body with the data.
          content:
            application/json:
              schema:
                type: object
                required: [email, name, picture]
                properties:
                  email: {type: string, format: email}
                  name: {type: string}
                  picture: {type: string, format: uri}
        '401':
          description: Missing JWT.
        '500':
          description: User dosen't exist.
      security:
        - bearerAuth: []

  /User/Logout:
    get:
      summary: User/Logout
      description: deprecated.
      responses:
        '200':
          description: deprecated
      security:
        - bearerAuth: []

  /User/Erase_user:
    delete:
      summary: User/Erase_user
      description: Erase a user from the DB.
      responses:
        '200':
          description: User erased.
        '401':
          description: Missing claims in JWT.
        '500':
          description: Error erasing user.
      security:
        - bearerAuth: []
